begin;

create table public.operational_documents(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,
 branch_id uuid not null references public.branches(id) on delete restrict,document_type text not null check(document_type in('sales_order','sales_delivery','purchase_order','goods_receipt')),
 document_number text not null,document_date date not null,contact_id uuid not null,source_document_id uuid,
 status text not null default 'draft' check(status in('draft','pending_approval','approved','rejected','posted','completed','cancelled','reversed')),
 total numeric(24,4) not null default 0 check(total>=0),notes text,closed_reason text,
 journal_entry_id uuid references public.journal_entries(id) on delete restrict,reversal_journal_id uuid references public.journal_entries(id) on delete restrict,
 submitted_by uuid references auth.users(id),submitted_at timestamptz,approved_by uuid references auth.users(id),approved_at timestamptz,
 rejected_by uuid references auth.users(id),rejected_at timestamptz,rejection_reason text,posted_by uuid references auth.users(id),posted_at timestamptz,
 reversed_by uuid references auth.users(id),reversed_at timestamptz,reversal_reason text,
 created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),updated_at timestamptz,updated_by uuid references auth.users(id),version integer not null default 1 check(version>0),
 unique(company_id,id),unique(company_id,document_number),
 foreign key(company_id,contact_id) references public.contacts(company_id,id) on delete restrict,
 foreign key(company_id,source_document_id) references public.operational_documents(company_id,id) on delete restrict
);
create table public.operational_document_lines(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,document_id uuid not null,
 line_number integer not null check(line_number>0),source_line_id uuid,product_id uuid not null,warehouse_id uuid not null,
 description text not null,quantity numeric(24,6) not null check(quantity>0),fulfilled_quantity numeric(24,6) not null default 0 check(fulfilled_quantity>=0 and fulfilled_quantity<=quantity),
 unit_amount numeric(24,6) not null check(unit_amount>=0),total numeric(24,4) not null check(total>=0),created_at timestamptz not null default now(),created_by uuid references auth.users(id),
 unique(document_id,line_number),foreign key(company_id,document_id) references public.operational_documents(company_id,id) on delete cascade,
 foreign key(company_id,product_id) references public.products(company_id,id) on delete restrict,foreign key(company_id,warehouse_id) references public.warehouses(company_id,id) on delete restrict,
 foreign key(source_line_id) references public.operational_document_lines(id) on delete restrict
);
create index operational_documents_company_type_status_idx on public.operational_documents(company_id,document_type,status,document_date desc);
create trigger operational_documents_updated before update on public.operational_documents for each row execute function public.set_updated_metadata();
create trigger operational_documents_audit after insert or update or delete on public.operational_documents for each row execute function public.audit_row_change();
alter table public.operational_documents enable row level security;alter table public.operational_document_lines enable row level security;
create policy operational_documents_read on public.operational_documents for select to authenticated using(public.current_user_has_permission(company_id,case when document_type like 'sales_%' then 'sales.read' else 'purchase.read' end));
create policy operational_lines_read on public.operational_document_lines for select to authenticated using(exists(select 1 from public.operational_documents document where document.id=operational_document_lines.document_id and document.company_id=operational_document_lines.company_id and public.current_user_has_permission(document.company_id,case when document.document_type like 'sales_%' then 'sales.read' else 'purchase.read' end)));
grant select on public.operational_documents,public.operational_document_lines to authenticated;

insert into public.account_mappings(company_id,mapping_code,account_id,created_by)
select account.company_id,'goods_received_not_invoiced',account.id,account.created_by from public.chart_of_accounts account
where account.code='2110' on conflict(company_id,mapping_code) do nothing;

create or replace function public.next_operational_number(p_company_id uuid,p_document_date date,p_branch_id uuid,p_document_type text)
returns text language plpgsql volatile security definer set search_path='' as $$
declare v_sequence public.document_sequences%rowtype;v_period text;v_value bigint;v_number text;v_width integer;v_code text:=case p_document_type when 'sales_order' then 'SO' when 'sales_delivery' then 'SD' when 'purchase_order' then 'PO' when 'goods_receipt' then 'GR' end;
begin
 if v_code is null then raise exception using message='Tipe dokumen operasional tidak valid.';end if;
 select * into v_sequence from public.document_sequences where company_id=p_company_id and document_type=v_code and branch_scope=coalesce(p_branch_id,'00000000-0000-0000-0000-000000000000'::uuid) for update;
 if not found then insert into public.document_sequences(company_id,branch_id,document_type,pattern,reset_frequency,created_by) values(p_company_id,p_branch_id,v_code,v_code||'-{YYYY}-{MM}-{####}','monthly',auth.uid()) returning * into v_sequence;end if;
 v_period:=to_char(p_document_date,'YYYY-MM');if v_sequence.current_period is distinct from v_period then v_value:=1;else v_value:=v_sequence.next_value;end if;update public.document_sequences set current_period=v_period,next_value=v_value+1 where id=v_sequence.id;
 v_number:=replace(replace(v_sequence.pattern,'{YYYY}',to_char(p_document_date,'YYYY')),'{MM}',to_char(p_document_date,'MM'));v_width:=coalesce(length((regexp_match(v_number,'\{(#+)\}'))[1]),0);return regexp_replace(v_number,'\{#+\}',lpad(v_value::text,v_width,'0'));
end;$$;revoke all on function public.next_operational_number(uuid,date,uuid,text) from public,anon,authenticated;

create or replace function public.save_operational_document(p_company_id uuid,p_document_id uuid,p_document_type text,p_header jsonb,p_lines jsonb,p_version integer default null)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_id uuid;v_current public.operational_documents%rowtype;v_line record;v_no integer:=0;v_total numeric(24,4):=0;v_domain text:=case when p_document_type like 'sales_%' then 'sales' else 'purchase' end;v_source_doc uuid;
 v_branch uuid:=(p_header->>'branch_id')::uuid;v_contact uuid:=(p_header->>'contact_id')::uuid;v_date date:=(p_header->>'document_date')::date;v_notes text:=nullif(trim(p_header->>'notes'),'');
begin
 if p_document_type not in('sales_order','sales_delivery','purchase_order','goods_receipt') or not public.current_user_has_permission(p_company_id,v_domain||case when p_document_id is null then '.create' else '.update' end) then raise exception using errcode='42501',message='Tidak memiliki izin menyimpan dokumen.';end if;
 if not exists(select 1 from public.branches where company_id=p_company_id and id=v_branch and is_active) then raise exception using message='Cabang aktif tidak ditemukan.';end if;
 if not exists(select 1 from public.contacts where company_id=p_company_id and id=v_contact and is_active and(case when v_domain='sales' then contact_type in('customer','both') else contact_type in('supplier','both') end)) then raise exception using message='Kontak aktif tidak valid.';end if;
 if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 or jsonb_array_length(p_lines)>200 then raise exception using message='Dokumen wajib memiliki 1 sampai 200 baris.';end if;
 if p_document_id is null then insert into public.operational_documents(company_id,branch_id,document_type,document_number,document_date,contact_id,notes,created_by) values(p_company_id,v_branch,p_document_type,'DRAFT-'||upper(substr(p_document_type,1,2))||'-'||substr(gen_random_uuid()::text,1,8),v_date,v_contact,v_notes,auth.uid()) returning id into v_id;
 else select * into v_current from public.operational_documents where company_id=p_company_id and id=p_document_id and document_type=p_document_type for update;if not found or v_current.status not in('draft','rejected') then raise exception using message='Draft tidak ditemukan.';end if;if v_current.version<>p_version then raise exception using errcode='40001',message='Dokumen telah diubah pengguna lain.';end if;v_source_doc:=v_current.source_document_id;update public.operational_documents set branch_id=v_branch,document_date=v_date,contact_id=v_contact,notes=v_notes,status='draft',rejection_reason=null,updated_by=auth.uid() where id=p_document_id;delete from public.operational_document_lines where document_id=p_document_id;v_id:=p_document_id;end if;
 for v_line in select * from jsonb_to_recordset(p_lines) as x(source_line_id uuid,product_id uuid,warehouse_id uuid,description text,quantity numeric,unit_amount numeric)
 loop v_no:=v_no+1;if v_line.quantity<=0 or v_line.unit_amount<0 or length(trim(v_line.description))<2 then raise exception using message='Baris dokumen tidak valid.';end if;
  if not exists(select 1 from public.products where company_id=p_company_id and id=v_line.product_id and product_type='inventory' and is_active) or not exists(select 1 from public.warehouses where company_id=p_company_id and id=v_line.warehouse_id and branch_id=v_branch and is_active) then raise exception using message='Produk atau gudang tidak valid.';end if;
  if v_source_doc is not null and not exists(select 1 from public.operational_document_lines source where source.id=v_line.source_line_id and source.document_id=v_source_doc and source.product_id=v_line.product_id and v_line.quantity<=source.quantity-source.fulfilled_quantity) then raise exception using message='Baris konversi melebihi sisa order.';end if;
  insert into public.operational_document_lines(company_id,document_id,line_number,source_line_id,product_id,warehouse_id,description,quantity,unit_amount,total,created_by) values(p_company_id,v_id,v_no,case when v_source_doc is null then null else v_line.source_line_id end,v_line.product_id,v_line.warehouse_id,trim(v_line.description),v_line.quantity,v_line.unit_amount,round(v_line.quantity*v_line.unit_amount,4),auth.uid());v_total:=v_total+round(v_line.quantity*v_line.unit_amount,4);
 end loop;update public.operational_documents set total=v_total where id=v_id;return v_id;
end;$$;

create or replace function public.delete_operational_draft(p_company_id uuid,p_document_id uuid,p_version integer)
returns void language plpgsql volatile security definer set search_path='' as $$ declare v_type text;v_domain text;begin select document_type into v_type from public.operational_documents where company_id=p_company_id and id=p_document_id;v_domain:=case when v_type like 'sales_%' then 'sales' else 'purchase' end;if not public.current_user_has_permission(p_company_id,v_domain||'.update') then raise exception using errcode='42501',message='Tidak memiliki izin menghapus draft.';end if;delete from public.operational_documents where company_id=p_company_id and id=p_document_id and version=p_version and status in('draft','rejected');if not found then raise exception using message='Draft berubah atau tidak dapat dihapus.';end if;end;$$;

create or replace function public.submit_operational_document(p_company_id uuid,p_document_id uuid)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.operational_documents%rowtype;v_request uuid;v_domain text;v_number text;
begin select * into v_doc from public.operational_documents where company_id=p_company_id and id=p_document_id and status in('draft','rejected') for update;if not found then raise exception using message='Draft dokumen tidak ditemukan.';end if;v_domain:=case when v_doc.document_type like 'sales_%' then 'sales' else 'purchase' end;if not public.current_user_has_permission(p_company_id,v_domain||'.submit') then raise exception using errcode='42501',message='Tidak memiliki izin submit dokumen.';end if;
 v_number:=case when v_doc.document_number like 'DRAFT-%' then public.next_operational_number(p_company_id,v_doc.document_date,v_doc.branch_id,v_doc.document_type) else v_doc.document_number end;
 insert into public.approval_requests(company_id,document_type,document_id,document_number,submitted_by,created_by) values(p_company_id,v_doc.document_type,p_document_id,v_number,auth.uid(),auth.uid()) on conflict(company_id,document_type,document_id) do update set document_number=excluded.document_number,status='pending',submitted_by=auth.uid(),submitted_at=now(),completed_at=null returning id into v_request;
 insert into public.approval_actions(company_id,request_id,step,action,actor_user_id) values(p_company_id,v_request,0,'submit',auth.uid());update public.operational_documents set document_number=v_number,status='pending_approval',submitted_by=auth.uid(),submitted_at=now(),updated_by=auth.uid() where id=p_document_id;return v_request;
end;$$;

create or replace function public.decide_operational_document(p_company_id uuid,p_document_id uuid,p_action text,p_comment text default null)
returns void language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.operational_documents%rowtype;v_request uuid;v_domain text;v_allow boolean:=false;
begin select * into v_doc from public.operational_documents where company_id=p_company_id and id=p_document_id and status='pending_approval' for update;if not found then raise exception using message='Dokumen menunggu persetujuan tidak ditemukan.';end if;v_domain:=case when v_doc.document_type like 'sales_%' then 'sales' else 'purchase' end;if p_action not in('approve','reject') or not public.current_user_has_permission(p_company_id,v_domain||'.approve') then raise exception using errcode='42501',message='Tidak memiliki izin persetujuan.';end if;
 select allow_self_approval into v_allow from public.company_settings where company_id=p_company_id;if not coalesce(v_allow,false) and v_doc.submitted_by=auth.uid() then raise exception using errcode='42501',message='Pembuat dokumen tidak boleh menyetujui sendiri.';end if;if p_action='reject' and length(trim(coalesce(p_comment,'')))<5 then raise exception using message='Alasan penolakan minimal lima karakter.';end if;
 select id into v_request from public.approval_requests where company_id=p_company_id and document_type=v_doc.document_type and document_id=p_document_id and status='pending' for update;update public.approval_requests set status=case p_action when 'approve' then 'approved' else 'rejected' end,completed_at=now() where id=v_request;insert into public.approval_actions(company_id,request_id,step,action,actor_user_id,comment) values(p_company_id,v_request,1,p_action,auth.uid(),nullif(trim(p_comment),''));
 if p_action='approve' then update public.operational_documents set status='approved',approved_by=auth.uid(),approved_at=now(),updated_by=auth.uid() where id=p_document_id;else update public.operational_documents set status='rejected',rejected_by=auth.uid(),rejected_at=now(),rejection_reason=trim(p_comment),updated_by=auth.uid() where id=p_document_id;end if;
end;$$;

create or replace function public.convert_operational_document(p_company_id uuid,p_source_id uuid)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_source public.operational_documents%rowtype;v_target_type text;v_domain text;v_target uuid;v_line record;v_no integer:=0;v_total numeric:=0;
begin select * into v_source from public.operational_documents where company_id=p_company_id and id=p_source_id and document_type in('sales_order','purchase_order') and status='approved' for update;if not found then raise exception using message='Order approved tidak ditemukan.';end if;v_domain:=case v_source.document_type when 'sales_order' then 'sales' else 'purchase' end;v_target_type:=case v_source.document_type when 'sales_order' then 'sales_delivery' else 'goods_receipt' end;if not public.current_user_has_permission(p_company_id,v_domain||'.create') then raise exception using errcode='42501',message='Tidak memiliki izin konversi order.';end if;
 insert into public.operational_documents(company_id,branch_id,document_type,document_number,document_date,contact_id,source_document_id,notes,created_by) values(p_company_id,v_source.branch_id,v_target_type,'DRAFT-'||upper(substr(v_target_type,1,2))||'-'||substr(gen_random_uuid()::text,1,8),current_date,v_source.contact_id,p_source_id,'Konversi dari '||v_source.document_number,auth.uid()) returning id into v_target;
 for v_line in select * from public.operational_document_lines where document_id=p_source_id and fulfilled_quantity<quantity order by line_number loop v_no:=v_no+1;insert into public.operational_document_lines(company_id,document_id,line_number,source_line_id,product_id,warehouse_id,description,quantity,unit_amount,total,created_by) values(p_company_id,v_target,v_no,v_line.id,v_line.product_id,v_line.warehouse_id,v_line.description,v_line.quantity-v_line.fulfilled_quantity,v_line.unit_amount,round((v_line.quantity-v_line.fulfilled_quantity)*v_line.unit_amount,4),auth.uid());v_total:=v_total+round((v_line.quantity-v_line.fulfilled_quantity)*v_line.unit_amount,4);end loop;if v_no=0 then raise exception using message='Order tidak memiliki kuantitas tersisa.';end if;update public.operational_documents set total=v_total where id=v_target;return v_target;
end;$$;

create or replace function public.post_operational_fulfillment(p_company_id uuid,p_document_id uuid,p_idempotency_key text)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.operational_documents%rowtype;v_line record;v_balance public.product_warehouses%rowtype;v_journal uuid;v_domain text;v_cost numeric(24,4);v_total numeric(24,4):=0;v_new_qty numeric(24,6);v_new_value numeric(24,4);v_new_avg numeric(24,6);v_grni uuid;v_no integer:=0;
begin select * into v_doc from public.operational_documents where company_id=p_company_id and id=p_document_id for update;if not found then raise exception using message='Dokumen fulfillment tidak ditemukan.';end if;if v_doc.status='posted' then return v_doc.journal_entry_id;end if;if v_doc.document_type not in('sales_delivery','goods_receipt') or v_doc.status<>'approved' then raise exception using message='Hanya delivery/receipt approved yang dapat diposting.';end if;v_domain:=case v_doc.document_type when 'sales_delivery' then 'sales' else 'purchase' end;if not public.current_user_has_permission(p_company_id,v_domain||'.post') then raise exception using errcode='42501',message='Tidak memiliki izin posting fulfillment.';end if;if not exists(select 1 from public.accounting_periods where company_id=p_company_id and v_doc.document_date between starts_on and ends_on and status='open') then raise exception using message='Periode akuntansi tidak terbuka.';end if;
 if v_doc.document_type='goods_receipt' then select account_id into v_grni from public.account_mappings where company_id=p_company_id and mapping_code='goods_received_not_invoiced';if v_grni is null then raise exception using message='Pemetaan GRNI belum dikonfigurasi.';end if;end if;
 insert into public.journal_entries(company_id,branch_id,journal_number,document_date,journal_date,posting_date,description,status,source_type,source_id,total_debit,total_credit,idempotency_key,posted_by,posted_at,created_by) values(p_company_id,v_doc.branch_id,v_doc.document_number||'/J',v_doc.document_date,v_doc.document_date,v_doc.document_date,'Fulfillment '||v_doc.document_number,'draft',v_doc.document_type,p_document_id,0,0,p_idempotency_key,auth.uid(),now(),auth.uid()) returning id into v_journal;
 for v_line in select line.*,product.inventory_account_id,product.cogs_account_id,product.name from public.operational_document_lines line join public.products product on product.id=line.product_id where line.document_id=p_document_id order by line.line_number loop
  insert into public.product_warehouses(company_id,product_id,warehouse_id,created_by) values(p_company_id,v_line.product_id,v_line.warehouse_id,auth.uid()) on conflict(company_id,product_id,warehouse_id) do nothing;select * into v_balance from public.product_warehouses where company_id=p_company_id and product_id=v_line.product_id and warehouse_id=v_line.warehouse_id for update;
  if v_doc.document_type='sales_delivery' then if v_line.quantity>v_balance.quantity_on_hand then raise exception using message='Stok '||v_line.name||' tidak mencukupi.';end if;v_cost:=round(v_line.quantity*v_balance.average_cost,4);v_new_qty:=v_balance.quantity_on_hand-v_line.quantity;v_new_value:=greatest(0,v_balance.inventory_value-v_cost);v_new_avg:=case when v_new_qty=0 then 0 else round(v_new_value/v_new_qty,6) end;
  else v_cost:=round(v_line.quantity*v_line.unit_amount,4);v_new_qty:=v_balance.quantity_on_hand+v_line.quantity;v_new_value:=v_balance.inventory_value+v_cost;v_new_avg:=round(v_new_value/v_new_qty,6);end if;
  update public.product_warehouses set quantity_on_hand=v_new_qty,inventory_value=v_new_value,average_cost=v_new_avg,last_movement_date=v_doc.document_date,updated_by=auth.uid() where id=v_balance.id;
  insert into public.inventory_movements(company_id,product_id,warehouse_id,movement_date,movement_type,quantity,unit_cost,total_cost,running_quantity,running_average_cost,source_type,source_id,source_line_id,created_by) values(p_company_id,v_line.product_id,v_line.warehouse_id,v_doc.document_date,case v_doc.document_type when 'sales_delivery' then 'issue' else 'receipt' end,case v_doc.document_type when 'sales_delivery' then -v_line.quantity else v_line.quantity end,case v_doc.document_type when 'sales_delivery' then v_balance.average_cost else v_line.unit_amount end,v_cost,v_new_qty,v_new_avg,v_doc.document_type,p_document_id,v_line.id,auth.uid());
  v_no:=v_no+1;insert into public.journal_lines(company_id,journal_entry_id,account_id,line_number,description,debit,credit,base_debit,base_credit,branch_id,created_by) values(p_company_id,v_journal,case v_doc.document_type when 'sales_delivery' then v_line.cogs_account_id else v_line.inventory_account_id end,v_no,v_line.name, v_cost,0,v_cost,0,v_doc.branch_id,auth.uid());v_no:=v_no+1;insert into public.journal_lines(company_id,journal_entry_id,account_id,line_number,description,debit,credit,base_debit,base_credit,branch_id,created_by) values(p_company_id,v_journal,case v_doc.document_type when 'sales_delivery' then v_line.inventory_account_id else v_grni end,v_no,v_line.name,0,v_cost,0,v_cost,v_doc.branch_id,auth.uid());v_total:=v_total+v_cost;
  if v_line.source_line_id is not null then update public.operational_document_lines set fulfilled_quantity=fulfilled_quantity+v_line.quantity where id=v_line.source_line_id and fulfilled_quantity+v_line.quantity<=quantity;if not found then raise exception using message='Kuantitas fulfillment melebihi order.';end if;end if;
 end loop;
 update public.journal_entries set total_debit=v_total,total_credit=v_total,status='posted' where id=v_journal;update public.operational_documents set status='posted',journal_entry_id=v_journal,posted_by=auth.uid(),posted_at=now(),updated_by=auth.uid() where id=p_document_id;
 if v_doc.source_document_id is not null and not exists(select 1 from public.operational_document_lines where document_id=v_doc.source_document_id and fulfilled_quantity<quantity) then update public.operational_documents set status='completed',closed_reason='Seluruh kuantitas telah dipenuhi',updated_by=auth.uid() where id=v_doc.source_document_id;end if;return v_journal;
exception when unique_violation then select id into v_journal from public.journal_entries where company_id=p_company_id and(idempotency_key=p_idempotency_key or(source_type=v_doc.document_type and source_id=p_document_id));if v_journal is null then raise;end if;return v_journal;
end;$$;

create or replace function public.reverse_operational_fulfillment(p_company_id uuid,p_document_id uuid,p_reversal_date date,p_reason text,p_idempotency_key text)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.operational_documents%rowtype;v_movement record;v_balance public.product_warehouses%rowtype;v_new_qty numeric;v_new_value numeric;v_new_avg numeric;v_reversal uuid;v_domain text;
begin select * into v_doc from public.operational_documents where company_id=p_company_id and id=p_document_id and status='posted' and document_type in('sales_delivery','goods_receipt') for update;if not found then raise exception using message='Fulfillment posted tidak ditemukan.';end if;v_domain:=case v_doc.document_type when 'sales_delivery' then 'sales' else 'purchase' end;if not public.current_user_has_permission(p_company_id,v_domain||'.post') or not public.current_user_has_permission(p_company_id,'journal.reverse') then raise exception using errcode='42501',message='Tidak memiliki izin reversal fulfillment.';end if;
 for v_movement in select * from public.inventory_movements where company_id=p_company_id and source_type=v_doc.document_type and source_id=p_document_id order by created_at desc loop if exists(select 1 from public.inventory_movements later where later.company_id=p_company_id and later.product_id=v_movement.product_id and later.warehouse_id=v_movement.warehouse_id and later.created_at>v_movement.created_at) then raise exception using message='Fulfillment tidak dapat direversal karena terdapat movement sesudahnya.';end if;select * into v_balance from public.product_warehouses where company_id=p_company_id and product_id=v_movement.product_id and warehouse_id=v_movement.warehouse_id for update;v_new_qty:=v_balance.quantity_on_hand-v_movement.quantity;v_new_value:=case when v_movement.quantity>0 then greatest(0,v_balance.inventory_value-v_movement.total_cost) else v_balance.inventory_value+v_movement.total_cost end;if v_new_qty<0 then raise exception using message='Reversal membuat stok negatif.';end if;v_new_avg:=case when v_new_qty=0 then 0 else round(v_new_value/v_new_qty,6) end;update public.product_warehouses set quantity_on_hand=v_new_qty,inventory_value=v_new_value,average_cost=v_new_avg,last_movement_date=p_reversal_date,updated_by=auth.uid() where id=v_balance.id;insert into public.inventory_movements(company_id,product_id,warehouse_id,movement_date,movement_type,quantity,unit_cost,total_cost,running_quantity,running_average_cost,source_type,source_id,source_line_id,created_by) values(p_company_id,v_movement.product_id,v_movement.warehouse_id,p_reversal_date,case when v_movement.quantity>0 then 'return_out' else 'return_in' end,-v_movement.quantity,v_movement.unit_cost,v_movement.total_cost,v_new_qty,v_new_avg,v_doc.document_type||'_reversal',p_document_id,v_movement.source_line_id,auth.uid());end loop;
 v_reversal:=public.reverse_journal_entry_core(p_company_id,v_doc.journal_entry_id,p_reversal_date,p_reason,p_idempotency_key);update public.operational_documents set status='reversed',reversal_journal_id=v_reversal,reversed_by=auth.uid(),reversed_at=now(),reversal_reason=trim(p_reason),updated_by=auth.uid() where id=p_document_id;
 if v_doc.source_document_id is not null then update public.operational_document_lines source set fulfilled_quantity=greatest(0,source.fulfilled_quantity-target.quantity) from public.operational_document_lines target where target.document_id=p_document_id and target.source_line_id=source.id;update public.operational_documents set status='approved',closed_reason=null,updated_by=auth.uid() where id=v_doc.source_document_id and status='completed';end if;return v_reversal;
end;$$;

revoke all on function public.save_operational_document(uuid,uuid,text,jsonb,jsonb,integer) from public,anon;revoke all on function public.delete_operational_draft(uuid,uuid,integer) from public,anon;revoke all on function public.submit_operational_document(uuid,uuid) from public,anon;revoke all on function public.decide_operational_document(uuid,uuid,text,text) from public,anon;revoke all on function public.convert_operational_document(uuid,uuid) from public,anon;revoke all on function public.post_operational_fulfillment(uuid,uuid,text) from public,anon;revoke all on function public.reverse_operational_fulfillment(uuid,uuid,date,text,text) from public,anon;
grant execute on function public.save_operational_document(uuid,uuid,text,jsonb,jsonb,integer) to authenticated;grant execute on function public.delete_operational_draft(uuid,uuid,integer) to authenticated;grant execute on function public.submit_operational_document(uuid,uuid) to authenticated;grant execute on function public.decide_operational_document(uuid,uuid,text,text) to authenticated;grant execute on function public.convert_operational_document(uuid,uuid) to authenticated;grant execute on function public.post_operational_fulfillment(uuid,uuid,text) to authenticated;grant execute on function public.reverse_operational_fulfillment(uuid,uuid,date,text,text) to authenticated;

commit;
