begin;

create table public.inventory_operations(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,
 branch_id uuid not null references public.branches(id) on delete restrict,operation_type text not null check(operation_type in('inventory_transfer','stock_count')),
 document_number text not null,operation_date date not null,source_warehouse_id uuid not null,destination_warehouse_id uuid,offset_account_id uuid,
 status text not null default 'draft' check(status in('draft','pending_approval','approved','rejected','posted','reversed')),
 reason text not null,journal_entry_id uuid references public.journal_entries(id) on delete restrict,reversal_journal_id uuid references public.journal_entries(id) on delete restrict,
 submitted_by uuid references auth.users(id),submitted_at timestamptz,approved_by uuid references auth.users(id),approved_at timestamptz,rejected_by uuid references auth.users(id),rejected_at timestamptz,rejection_reason text,
 posted_by uuid references auth.users(id),posted_at timestamptz,reversed_by uuid references auth.users(id),reversed_at timestamptz,reversal_reason text,
 created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),updated_at timestamptz,updated_by uuid references auth.users(id),version integer not null default 1 check(version>0),
 unique(company_id,id),unique(company_id,document_number),
 foreign key(company_id,source_warehouse_id) references public.warehouses(company_id,id) on delete restrict,
 foreign key(company_id,destination_warehouse_id) references public.warehouses(company_id,id) on delete restrict,
 foreign key(company_id,offset_account_id) references public.chart_of_accounts(company_id,id) on delete restrict,
 check((operation_type='inventory_transfer' and destination_warehouse_id is not null and destination_warehouse_id<>source_warehouse_id and offset_account_id is null) or(operation_type='stock_count' and destination_warehouse_id is null and offset_account_id is not null))
);
create table public.inventory_operation_lines(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,operation_id uuid not null,line_number integer not null check(line_number>0),product_id uuid not null,
 quantity numeric(24,6),expected_quantity numeric(24,6),counted_quantity numeric(24,6),unit_cost numeric(24,6) not null default 0 check(unit_cost>=0),total_cost numeric(24,4) not null default 0 check(total_cost>=0),
 created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(operation_id,line_number),unique(operation_id,product_id),
 foreign key(company_id,operation_id) references public.inventory_operations(company_id,id) on delete cascade,foreign key(company_id,product_id) references public.products(company_id,id) on delete restrict,
 check((quantity is not null and quantity>0 and expected_quantity is null and counted_quantity is null) or(quantity is null and expected_quantity is not null and expected_quantity>=0 and counted_quantity is not null and counted_quantity>=0))
);
create index inventory_operations_company_type_status_idx on public.inventory_operations(company_id,operation_type,status,operation_date desc);
create trigger inventory_operations_updated before update on public.inventory_operations for each row execute function public.set_updated_metadata();
create trigger inventory_operations_audit after insert or update or delete on public.inventory_operations for each row execute function public.audit_row_change();
alter table public.inventory_operations enable row level security;alter table public.inventory_operation_lines enable row level security;
create policy inventory_operations_read on public.inventory_operations for select to authenticated using(public.current_user_has_permission(company_id,'inventory.read'));
create policy inventory_operation_lines_read on public.inventory_operation_lines for select to authenticated using(public.current_user_has_permission(company_id,'inventory.read'));
grant select on public.inventory_operations,public.inventory_operation_lines to authenticated;

create or replace function public.next_inventory_operation_number(p_company_id uuid,p_operation_date date,p_branch_id uuid,p_operation_type text)
returns text language plpgsql volatile security definer set search_path='' as $$
declare v_sequence public.document_sequences%rowtype;v_period text;v_value bigint;v_number text;v_width integer;v_code text:=case p_operation_type when 'inventory_transfer' then 'IT' when 'stock_count' then 'SC' end;
begin if v_code is null then raise exception using message='Tipe operasi stok tidak valid.';end if;select * into v_sequence from public.document_sequences where company_id=p_company_id and document_type=v_code and branch_scope=coalesce(p_branch_id,'00000000-0000-0000-0000-000000000000'::uuid) for update;if not found then insert into public.document_sequences(company_id,branch_id,document_type,pattern,reset_frequency,created_by) values(p_company_id,p_branch_id,v_code,v_code||'-{YYYY}-{MM}-{####}','monthly',auth.uid()) returning * into v_sequence;end if;v_period:=to_char(p_operation_date,'YYYY-MM');if v_sequence.current_period is distinct from v_period then v_value:=1;else v_value:=v_sequence.next_value;end if;update public.document_sequences set current_period=v_period,next_value=v_value+1 where id=v_sequence.id;v_number:=replace(replace(v_sequence.pattern,'{YYYY}',to_char(p_operation_date,'YYYY')),'{MM}',to_char(p_operation_date,'MM'));v_width:=coalesce(length((regexp_match(v_number,'\{(#+)\}'))[1]),0);return regexp_replace(v_number,'\{#+\}',lpad(v_value::text,v_width,'0'));end;$$;
revoke all on function public.next_inventory_operation_number(uuid,date,uuid,text) from public,anon,authenticated;

create or replace function public.save_inventory_operation(p_company_id uuid,p_operation_id uuid,p_operation_type text,p_header jsonb,p_lines jsonb,p_version integer default null)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_id uuid;v_doc public.inventory_operations%rowtype;v_line record;v_no integer:=0;v_expected numeric;v_branch uuid:=(p_header->>'branch_id')::uuid;v_source uuid:=(p_header->>'source_warehouse_id')::uuid;v_destination uuid:=nullif(p_header->>'destination_warehouse_id','')::uuid;v_offset uuid:=nullif(p_header->>'offset_account_id','')::uuid;v_date date:=(p_header->>'operation_date')::date;v_reason text:=trim(p_header->>'reason');
begin
 if not public.current_user_has_permission(p_company_id,'inventory.write') then raise exception using errcode='42501',message='Tidak memiliki izin menyimpan operasi stok.';end if;
 if p_operation_type not in('inventory_transfer','stock_count') or length(v_reason)<5 then raise exception using message='Jenis atau alasan operasi stok tidak valid.';end if;
 if not exists(select 1 from public.warehouses where company_id=p_company_id and id=v_source and branch_id=v_branch and is_active) then raise exception using message='Gudang sumber aktif tidak ditemukan pada cabang.';end if;
 if p_operation_type='inventory_transfer' and(v_destination is null or v_destination=v_source or not exists(select 1 from public.warehouses where company_id=p_company_id and id=v_destination and is_active)) then raise exception using message='Gudang tujuan transfer tidak valid.';end if;
 if p_operation_type='stock_count' and(v_offset is null or not exists(select 1 from public.chart_of_accounts where company_id=p_company_id and id=v_offset and is_active and allow_manual_entry)) then raise exception using message='Akun lawan opname tidak valid.';end if;
 if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 or jsonb_array_length(p_lines)>500 then raise exception using message='Operasi stok wajib memiliki 1 sampai 500 baris.';end if;
 if p_operation_id is null then insert into public.inventory_operations(company_id,branch_id,operation_type,document_number,operation_date,source_warehouse_id,destination_warehouse_id,offset_account_id,reason,created_by) values(p_company_id,v_branch,p_operation_type,'DRAFT-'||upper(substr(p_operation_type,1,2))||'-'||substr(gen_random_uuid()::text,1,8),v_date,v_source,case when p_operation_type='inventory_transfer' then v_destination end,case when p_operation_type='stock_count' then v_offset end,v_reason,auth.uid()) returning id into v_id;
 else select * into v_doc from public.inventory_operations where company_id=p_company_id and id=p_operation_id and operation_type=p_operation_type for update;if not found or v_doc.status not in('draft','rejected') then raise exception using message='Draft operasi stok tidak ditemukan.';end if;if v_doc.version<>p_version then raise exception using errcode='40001',message='Operasi stok telah diubah pengguna lain.';end if;update public.inventory_operations set branch_id=v_branch,operation_date=v_date,source_warehouse_id=v_source,destination_warehouse_id=case when p_operation_type='inventory_transfer' then v_destination end,offset_account_id=case when p_operation_type='stock_count' then v_offset end,reason=v_reason,status='draft',rejection_reason=null,updated_by=auth.uid() where id=p_operation_id;delete from public.inventory_operation_lines where operation_id=p_operation_id;v_id:=p_operation_id;end if;
 for v_line in select * from jsonb_to_recordset(p_lines) as x(product_id uuid,quantity numeric,counted_quantity numeric) loop v_no:=v_no+1;if not exists(select 1 from public.products where company_id=p_company_id and id=v_line.product_id and product_type='inventory' and is_active) then raise exception using message='Produk persediaan aktif tidak ditemukan.';end if;select coalesce(quantity_on_hand,0) into v_expected from public.product_warehouses where company_id=p_company_id and warehouse_id=v_source and product_id=v_line.product_id;if p_operation_type='inventory_transfer' then if coalesce(v_line.quantity,0)<=0 then raise exception using message='Kuantitas transfer harus lebih dari nol.';end if;insert into public.inventory_operation_lines(company_id,operation_id,line_number,product_id,quantity,created_by) values(p_company_id,v_id,v_no,v_line.product_id,v_line.quantity,auth.uid());else if coalesce(v_line.counted_quantity,-1)<0 then raise exception using message='Kuantitas hitung tidak boleh negatif.';end if;insert into public.inventory_operation_lines(company_id,operation_id,line_number,product_id,expected_quantity,counted_quantity,created_by) values(p_company_id,v_id,v_no,v_line.product_id,coalesce(v_expected,0),v_line.counted_quantity,auth.uid());end if;end loop;return v_id;
end;$$;

create or replace function public.delete_inventory_operation(p_company_id uuid,p_operation_id uuid,p_version integer)
returns void language plpgsql volatile security definer set search_path='' as $$ begin if not public.current_user_has_permission(p_company_id,'inventory.write') then raise exception using errcode='42501',message='Tidak memiliki izin menghapus draft.';end if;delete from public.inventory_operations where company_id=p_company_id and id=p_operation_id and version=p_version and status in('draft','rejected');if not found then raise exception using message='Draft berubah atau tidak dapat dihapus.';end if;end;$$;

create or replace function public.submit_inventory_operation(p_company_id uuid,p_operation_id uuid)
returns uuid language plpgsql volatile security definer set search_path='' as $$ declare v_doc public.inventory_operations%rowtype;v_request uuid;v_number text;begin if not public.current_user_has_permission(p_company_id,'inventory.submit') then raise exception using errcode='42501',message='Tidak memiliki izin submit operasi stok.';end if;select * into v_doc from public.inventory_operations where company_id=p_company_id and id=p_operation_id and status in('draft','rejected') for update;if not found then raise exception using message='Draft operasi stok tidak ditemukan.';end if;v_number:=case when v_doc.document_number like 'DRAFT-%' then public.next_inventory_operation_number(p_company_id,v_doc.operation_date,v_doc.branch_id,v_doc.operation_type) else v_doc.document_number end;insert into public.approval_requests(company_id,document_type,document_id,document_number,submitted_by,created_by) values(p_company_id,v_doc.operation_type,p_operation_id,v_number,auth.uid(),auth.uid()) on conflict(company_id,document_type,document_id) do update set document_number=excluded.document_number,status='pending',submitted_by=auth.uid(),submitted_at=now(),completed_at=null returning id into v_request;insert into public.approval_actions(company_id,request_id,step,action,actor_user_id) values(p_company_id,v_request,0,'submit',auth.uid());update public.inventory_operations set document_number=v_number,status='pending_approval',submitted_by=auth.uid(),submitted_at=now(),updated_by=auth.uid() where id=p_operation_id;return v_request;end;$$;

create or replace function public.decide_inventory_operation(p_company_id uuid,p_operation_id uuid,p_action text,p_comment text default null)
returns void language plpgsql volatile security definer set search_path='' as $$ declare v_doc public.inventory_operations%rowtype;v_request uuid;v_allow boolean:=false;begin if p_action not in('approve','reject') or not public.current_user_has_permission(p_company_id,'inventory.approve') then raise exception using errcode='42501',message='Tidak memiliki izin persetujuan operasi stok.';end if;select * into v_doc from public.inventory_operations where company_id=p_company_id and id=p_operation_id and status='pending_approval' for update;if not found then raise exception using message='Operasi stok menunggu persetujuan tidak ditemukan.';end if;select allow_self_approval into v_allow from public.company_settings where company_id=p_company_id;if not coalesce(v_allow,false) and v_doc.submitted_by=auth.uid() then raise exception using errcode='42501',message='Pembuat tidak boleh menyetujui sendiri.';end if;if p_action='reject' and length(trim(coalesce(p_comment,'')))<5 then raise exception using message='Alasan penolakan minimal lima karakter.';end if;select id into v_request from public.approval_requests where company_id=p_company_id and document_type=v_doc.operation_type and document_id=p_operation_id and status='pending' for update;update public.approval_requests set status=case p_action when 'approve' then 'approved' else 'rejected' end,completed_at=now() where id=v_request;insert into public.approval_actions(company_id,request_id,step,action,actor_user_id,comment) values(p_company_id,v_request,1,p_action,auth.uid(),nullif(trim(p_comment),''));if p_action='approve' then update public.inventory_operations set status='approved',approved_by=auth.uid(),approved_at=now(),updated_by=auth.uid() where id=p_operation_id;else update public.inventory_operations set status='rejected',rejected_by=auth.uid(),rejected_at=now(),rejection_reason=trim(p_comment),updated_by=auth.uid() where id=p_operation_id;end if;end;$$;

create or replace function public.post_inventory_operation(p_company_id uuid,p_operation_id uuid,p_idempotency_key text)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.inventory_operations%rowtype;v_line record;v_source public.product_warehouses%rowtype;v_destination public.product_warehouses%rowtype;v_journal uuid;v_cost numeric;v_difference numeric;v_new_qty numeric;v_new_value numeric;v_new_avg numeric;v_total numeric:=0;v_no integer:=0;
begin
 if not public.current_user_has_permission(p_company_id,'inventory.post') then raise exception using errcode='42501',message='Tidak memiliki izin posting operasi stok.';end if;select * into v_doc from public.inventory_operations where company_id=p_company_id and id=p_operation_id for update;if not found then raise exception using message='Operasi stok tidak ditemukan.';end if;if v_doc.status='posted' then return v_doc.journal_entry_id;end if;if v_doc.status<>'approved' then raise exception using message='Hanya operasi approved yang dapat diposting.';end if;
 if v_doc.operation_type='stock_count' then if not exists(select 1 from public.accounting_periods where company_id=p_company_id and v_doc.operation_date between starts_on and ends_on and status='open') then raise exception using message='Periode akuntansi tidak terbuka.';end if;insert into public.journal_entries(company_id,branch_id,journal_number,document_date,journal_date,posting_date,description,status,source_type,source_id,total_debit,total_credit,idempotency_key,posted_by,posted_at,created_by) values(p_company_id,v_doc.branch_id,v_doc.document_number||'/J',v_doc.operation_date,v_doc.operation_date,v_doc.operation_date,'Stock opname '||v_doc.document_number,'draft','stock_count',p_operation_id,0,0,p_idempotency_key,auth.uid(),now(),auth.uid()) returning id into v_journal;end if;
 for v_line in select line.*,product.inventory_account_id,product.purchase_price,product.name from public.inventory_operation_lines line join public.products product on product.id=line.product_id where line.operation_id=p_operation_id order by line.line_number loop
  insert into public.product_warehouses(company_id,product_id,warehouse_id,created_by) values(p_company_id,v_line.product_id,v_doc.source_warehouse_id,auth.uid()) on conflict(company_id,product_id,warehouse_id) do nothing;select * into v_source from public.product_warehouses where company_id=p_company_id and product_id=v_line.product_id and warehouse_id=v_doc.source_warehouse_id for update;
  if v_doc.operation_type='inventory_transfer' then
   if v_line.quantity>v_source.quantity_on_hand then raise exception using message='Stok '||v_line.name||' tidak mencukupi untuk transfer.';end if;insert into public.product_warehouses(company_id,product_id,warehouse_id,created_by) values(p_company_id,v_line.product_id,v_doc.destination_warehouse_id,auth.uid()) on conflict(company_id,product_id,warehouse_id) do nothing;select * into v_destination from public.product_warehouses where company_id=p_company_id and product_id=v_line.product_id and warehouse_id=v_doc.destination_warehouse_id for update;v_cost:=round(v_line.quantity*v_source.average_cost,4);
   update public.product_warehouses set quantity_on_hand=quantity_on_hand-v_line.quantity,inventory_value=greatest(0,inventory_value-v_cost),average_cost=case when quantity_on_hand-v_line.quantity=0 then 0 else round(greatest(0,inventory_value-v_cost)/(quantity_on_hand-v_line.quantity),6) end,last_movement_date=v_doc.operation_date,updated_by=auth.uid() where id=v_source.id;
   v_new_qty:=v_destination.quantity_on_hand+v_line.quantity;v_new_value:=v_destination.inventory_value+v_cost;v_new_avg:=case when v_new_qty=0 then 0 else round(v_new_value/v_new_qty,6) end;update public.product_warehouses set quantity_on_hand=v_new_qty,inventory_value=v_new_value,average_cost=v_new_avg,last_movement_date=v_doc.operation_date,updated_by=auth.uid() where id=v_destination.id;
   insert into public.inventory_movements(company_id,product_id,warehouse_id,movement_date,movement_type,quantity,unit_cost,total_cost,running_quantity,running_average_cost,source_type,source_id,source_line_id,created_by) values(p_company_id,v_line.product_id,v_doc.source_warehouse_id,v_doc.operation_date,'transfer_out',-v_line.quantity,v_source.average_cost,v_cost,v_source.quantity_on_hand-v_line.quantity,case when v_source.quantity_on_hand-v_line.quantity=0 then 0 else v_source.average_cost end,'inventory_transfer_out',p_operation_id,v_line.id,auth.uid()),(p_company_id,v_line.product_id,v_doc.destination_warehouse_id,v_doc.operation_date,'transfer_in',v_line.quantity,v_source.average_cost,v_cost,v_new_qty,v_new_avg,'inventory_transfer_in',p_operation_id,v_line.id,auth.uid());update public.inventory_operation_lines set unit_cost=v_source.average_cost,total_cost=v_cost where id=v_line.id;
  else
   if v_source.quantity_on_hand<>v_line.expected_quantity then raise exception using message='Saldo '||v_line.name||' berubah setelah snapshot; buat opname baru.';end if;v_difference:=v_line.counted_quantity-v_line.expected_quantity;if v_difference=0 then continue;end if;v_cost:=coalesce(nullif(v_source.average_cost,0),nullif(v_line.purchase_price,0));if v_cost is null then raise exception using message='Biaya produk '||v_line.name||' belum tersedia.';end if;v_total:=v_total+round(abs(v_difference)*v_cost,4);v_new_qty:=v_line.counted_quantity;v_new_value:=case when v_difference>0 then v_source.inventory_value+round(v_difference*v_cost,4) else greatest(0,v_source.inventory_value-round(abs(v_difference)*v_source.average_cost,4)) end;v_new_avg:=case when v_new_qty=0 then 0 else round(v_new_value/v_new_qty,6) end;update public.product_warehouses set quantity_on_hand=v_new_qty,inventory_value=v_new_value,average_cost=v_new_avg,last_movement_date=v_doc.operation_date,updated_by=auth.uid() where id=v_source.id;update public.inventory_operation_lines set unit_cost=v_cost,total_cost=round(abs(v_difference)*v_cost,4) where id=v_line.id;insert into public.inventory_movements(company_id,product_id,warehouse_id,movement_date,movement_type,quantity,unit_cost,total_cost,running_quantity,running_average_cost,source_type,source_id,source_line_id,created_by) values(p_company_id,v_line.product_id,v_doc.source_warehouse_id,v_doc.operation_date,case when v_difference>0 then 'adjustment_in' else 'adjustment_out' end,v_difference,v_cost,round(abs(v_difference)*v_cost,4),v_new_qty,v_new_avg,'stock_count',p_operation_id,v_line.id,auth.uid());v_no:=v_no+1;insert into public.journal_lines(company_id,journal_entry_id,account_id,line_number,description,debit,credit,base_debit,base_credit,branch_id,created_by) values(p_company_id,v_journal,v_line.inventory_account_id,v_no,'Selisih opname: '||v_line.name,case when v_difference>0 then round(v_difference*v_cost,4) else 0 end,case when v_difference<0 then round(abs(v_difference)*v_cost,4) else 0 end,case when v_difference>0 then round(v_difference*v_cost,4) else 0 end,case when v_difference<0 then round(abs(v_difference)*v_cost,4) else 0 end,v_doc.branch_id,auth.uid());v_no:=v_no+1;insert into public.journal_lines(company_id,journal_entry_id,account_id,line_number,description,debit,credit,base_debit,base_credit,branch_id,created_by) values(p_company_id,v_journal,v_doc.offset_account_id,v_no,'Lawan selisih opname: '||v_line.name,case when v_difference<0 then round(abs(v_difference)*v_cost,4) else 0 end,case when v_difference>0 then round(v_difference*v_cost,4) else 0 end,case when v_difference<0 then round(abs(v_difference)*v_cost,4) else 0 end,case when v_difference>0 then round(v_difference*v_cost,4) else 0 end,v_doc.branch_id,auth.uid());
  end if;
 end loop;
 if v_doc.operation_type='stock_count' then if v_total=0 then delete from public.journal_entries where id=v_journal;v_journal:=null;else update public.journal_entries set total_debit=v_total,total_credit=v_total,status='posted' where id=v_journal;end if;end if;update public.inventory_operations set status='posted',journal_entry_id=v_journal,posted_by=auth.uid(),posted_at=now(),updated_by=auth.uid() where id=p_operation_id;return v_journal;
exception when unique_violation then select journal_entry_id into v_journal from public.inventory_operations where id=p_operation_id;if v_journal is null and v_doc.operation_type='stock_count' then select id into v_journal from public.journal_entries where company_id=p_company_id and idempotency_key=p_idempotency_key;end if;return v_journal;end;$$;

create or replace function public.reverse_inventory_operation(p_company_id uuid,p_operation_id uuid,p_reversal_date date,p_reason text,p_idempotency_key text)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_doc public.inventory_operations%rowtype;v_move public.inventory_movements%rowtype;v_balance public.product_warehouses%rowtype;v_new_qty numeric;v_new_value numeric;v_new_avg numeric;v_reversal uuid;
begin if not public.current_user_has_permission(p_company_id,'inventory.reverse') then raise exception using errcode='42501',message='Tidak memiliki izin reversal operasi stok.';end if;if length(trim(p_reason))<5 then raise exception using message='Alasan reversal minimal lima karakter.';end if;select * into v_doc from public.inventory_operations where company_id=p_company_id and id=p_operation_id and status='posted' for update;if not found then raise exception using message='Operasi stok posted tidak ditemukan.';end if;
 for v_move in select * from public.inventory_movements where company_id=p_company_id and source_id=p_operation_id and source_type in('inventory_transfer_out','inventory_transfer_in','stock_count') order by created_at desc loop if exists(select 1 from public.inventory_movements later where later.company_id=p_company_id and later.product_id=v_move.product_id and later.warehouse_id=v_move.warehouse_id and later.created_at>v_move.created_at) then raise exception using message='Reversal diblokir karena ada movement stok berikutnya.';end if;select * into v_balance from public.product_warehouses where company_id=p_company_id and product_id=v_move.product_id and warehouse_id=v_move.warehouse_id for update;v_new_qty:=v_balance.quantity_on_hand-v_move.quantity;if v_new_qty<0 then raise exception using message='Reversal akan membuat stok negatif.';end if;v_new_value:=case when v_move.quantity>0 then greatest(0,v_balance.inventory_value-v_move.total_cost) else v_balance.inventory_value+v_move.total_cost end;v_new_avg:=case when v_new_qty=0 then 0 else round(v_new_value/v_new_qty,6) end;update public.product_warehouses set quantity_on_hand=v_new_qty,inventory_value=v_new_value,average_cost=v_new_avg,last_movement_date=p_reversal_date,updated_by=auth.uid() where id=v_balance.id;insert into public.inventory_movements(company_id,product_id,warehouse_id,movement_date,movement_type,quantity,unit_cost,total_cost,running_quantity,running_average_cost,source_type,source_id,source_line_id,created_by) values(p_company_id,v_move.product_id,v_move.warehouse_id,p_reversal_date,case when v_move.quantity>0 then 'transfer_out' else 'transfer_in' end,-v_move.quantity,v_move.unit_cost,v_move.total_cost,v_new_qty,v_new_avg,v_move.source_type||'_reversal',p_operation_id,v_move.source_line_id,auth.uid());end loop;
 if v_doc.journal_entry_id is not null then if not public.current_user_has_permission(p_company_id,'journal.reverse') then raise exception using errcode='42501',message='Tidak memiliki izin reversal jurnal opname.';end if;v_reversal:=public.reverse_journal_entry_core(p_company_id,v_doc.journal_entry_id,p_reversal_date,p_reason,p_idempotency_key);end if;update public.inventory_operations set status='reversed',reversal_journal_id=v_reversal,reversed_by=auth.uid(),reversed_at=now(),reversal_reason=trim(p_reason),updated_by=auth.uid() where id=p_operation_id;return v_reversal;end;$$;

revoke all on function public.save_inventory_operation(uuid,uuid,text,jsonb,jsonb,integer) from public,anon;revoke all on function public.delete_inventory_operation(uuid,uuid,integer) from public,anon;revoke all on function public.submit_inventory_operation(uuid,uuid) from public,anon;revoke all on function public.decide_inventory_operation(uuid,uuid,text,text) from public,anon;revoke all on function public.post_inventory_operation(uuid,uuid,text) from public,anon;revoke all on function public.reverse_inventory_operation(uuid,uuid,date,text,text) from public,anon;
grant execute on function public.save_inventory_operation(uuid,uuid,text,jsonb,jsonb,integer) to authenticated;grant execute on function public.delete_inventory_operation(uuid,uuid,integer) to authenticated;grant execute on function public.submit_inventory_operation(uuid,uuid) to authenticated;grant execute on function public.decide_inventory_operation(uuid,uuid,text,text) to authenticated;grant execute on function public.post_inventory_operation(uuid,uuid,text) to authenticated;grant execute on function public.reverse_inventory_operation(uuid,uuid,date,text,text) to authenticated;

commit;
