begin;

create table public.bank_reconciliations(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,bank_account_id uuid not null,
 statement_date date not null,opening_balance numeric(24,4) not null,closing_balance numeric(24,4) not null,status text not null default 'draft' check(status in('draft','finalized')),
 finalized_at timestamptz,finalized_by uuid references auth.users(id),created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),updated_at timestamptz,updated_by uuid references auth.users(id),version integer not null default 1 check(version>0),
 unique(company_id,id),unique(company_id,bank_account_id,statement_date),foreign key(company_id,bank_account_id) references public.bank_accounts(company_id,id) on delete restrict
);
create table public.bank_statement_lines(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete restrict,reconciliation_id uuid not null,line_number integer not null check(line_number>0),transaction_date date not null,description text not null,reference text,amount numeric(24,4) not null check(amount<>0),
 status text not null default 'unmatched' check(status in('unmatched','matched','adjusted')),matched_type text,matched_id uuid,adjustment_journal_id uuid references public.journal_entries(id) on delete restrict,created_at timestamptz not null default now(),created_by uuid references auth.users(id),
 unique(reconciliation_id,line_number),foreign key(company_id,reconciliation_id) references public.bank_reconciliations(company_id,id) on delete cascade,
 check((status='unmatched' and matched_type is null and matched_id is null and adjustment_journal_id is null) or(status='matched' and matched_type is not null and matched_id is not null and adjustment_journal_id is null) or(status='adjusted' and adjustment_journal_id is not null))
);
create index bank_reconciliations_company_status_idx on public.bank_reconciliations(company_id,status,statement_date desc);
create trigger bank_reconciliations_updated before update on public.bank_reconciliations for each row execute function public.set_updated_metadata();
create trigger bank_reconciliations_audit after insert or update or delete on public.bank_reconciliations for each row execute function public.audit_row_change();
alter table public.bank_reconciliations enable row level security;alter table public.bank_statement_lines enable row level security;
create policy bank_reconciliations_read on public.bank_reconciliations for select to authenticated using(public.current_user_has_permission(company_id,'report.financial.read'));
create policy bank_statement_lines_read on public.bank_statement_lines for select to authenticated using(public.current_user_has_permission(company_id,'report.financial.read'));
grant select on public.bank_reconciliations,public.bank_statement_lines to authenticated;

create or replace function public.save_bank_reconciliation(p_company_id uuid,p_reconciliation_id uuid,p_header jsonb,p_lines jsonb,p_version integer default null)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_id uuid;v_doc public.bank_reconciliations%rowtype;v_line record;v_no integer:=0;v_bank uuid:=(p_header->>'bank_account_id')::uuid;v_date date:=(p_header->>'statement_date')::date;v_opening numeric:=(p_header->>'opening_balance')::numeric;v_closing numeric:=(p_header->>'closing_balance')::numeric;
begin if not public.current_user_has_permission(p_company_id,'settings.manage') then raise exception using errcode='42501',message='Tidak memiliki izin rekonsiliasi bank.';end if;if not exists(select 1 from public.bank_accounts where company_id=p_company_id and id=v_bank and is_active) then raise exception using message='Akun bank aktif tidak ditemukan.';end if;if jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0 or jsonb_array_length(p_lines)>5000 then raise exception using message='Statement wajib memiliki 1 sampai 5000 baris.';end if;
 if p_reconciliation_id is null then insert into public.bank_reconciliations(company_id,bank_account_id,statement_date,opening_balance,closing_balance,created_by) values(p_company_id,v_bank,v_date,v_opening,v_closing,auth.uid()) returning id into v_id;else select * into v_doc from public.bank_reconciliations where company_id=p_company_id and id=p_reconciliation_id for update;if not found or v_doc.status<>'draft' then raise exception using message='Draft rekonsiliasi tidak ditemukan.';end if;if v_doc.version<>p_version then raise exception using errcode='40001',message='Rekonsiliasi telah diubah pengguna lain.';end if;if exists(select 1 from public.bank_statement_lines where reconciliation_id=p_reconciliation_id and status<>'unmatched') then raise exception using message='Statement yang sudah memiliki match tidak dapat diganti.';end if;update public.bank_reconciliations set bank_account_id=v_bank,statement_date=v_date,opening_balance=v_opening,closing_balance=v_closing,updated_by=auth.uid() where id=p_reconciliation_id;delete from public.bank_statement_lines where reconciliation_id=p_reconciliation_id;v_id:=p_reconciliation_id;end if;
 for v_line in select * from jsonb_to_recordset(p_lines) as x(transaction_date date,description text,reference text,amount numeric) loop v_no:=v_no+1;if v_line.amount=0 or length(trim(v_line.description))<2 then raise exception using message='Baris statement tidak valid.';end if;insert into public.bank_statement_lines(company_id,reconciliation_id,line_number,transaction_date,description,reference,amount,created_by) values(p_company_id,v_id,v_no,v_line.transaction_date,trim(v_line.description),nullif(trim(v_line.reference),''),v_line.amount,auth.uid());end loop;return v_id;end;$$;

create or replace function public.match_bank_statement_line(p_company_id uuid,p_line_id uuid,p_matched_type text,p_matched_id uuid)
returns void language plpgsql volatile security definer set search_path='' as $$
declare v_line public.bank_statement_lines%rowtype;v_doc public.bank_reconciliations%rowtype;v_valid boolean:=false;
begin if not public.current_user_has_permission(p_company_id,'settings.manage') then raise exception using errcode='42501',message='Tidak memiliki izin matching bank.';end if;select line.* into v_line from public.bank_statement_lines line join public.bank_reconciliations reconciliation on reconciliation.id=line.reconciliation_id where line.company_id=p_company_id and line.id=p_line_id and line.status='unmatched' and reconciliation.status='draft' for update;if not found then raise exception using message='Baris unmatched tidak ditemukan.';end if;select * into v_doc from public.bank_reconciliations where id=v_line.reconciliation_id;
 if p_matched_type='customer_receipt' then select exists(select 1 from public.customer_receipts where company_id=p_company_id and id=p_matched_id and bank_account_id=v_doc.bank_account_id and status='posted' and amount=abs(v_line.amount) and v_line.amount>0) into v_valid;
 elsif p_matched_type='supplier_payment' then select exists(select 1 from public.supplier_payments where company_id=p_company_id and id=p_matched_id and bank_account_id=v_doc.bank_account_id and status='posted' and amount=abs(v_line.amount) and v_line.amount<0) into v_valid;
 elsif p_matched_type='cash_transaction' then select exists(select 1 from public.cash_transactions where company_id=p_company_id and id=p_matched_id and status='posted' and((transaction_type='cash_in' and bank_account_id=v_doc.bank_account_id and amount=v_line.amount)or(transaction_type='cash_out' and bank_account_id=v_doc.bank_account_id and -amount=v_line.amount)or(transaction_type='bank_transfer' and((destination_bank_account_id=v_doc.bank_account_id and amount=v_line.amount)or(bank_account_id=v_doc.bank_account_id and -amount=v_line.amount))))) into v_valid;end if;
 if not v_valid then raise exception using message='Transaksi posted tidak cocok dengan akun dan nilai statement.';end if;if exists(select 1 from public.bank_statement_lines used where used.company_id=p_company_id and used.matched_type=p_matched_type and used.matched_id=p_matched_id and used.status='matched') then raise exception using message='Transaksi sudah dicocokkan ke baris lain.';end if;update public.bank_statement_lines set status='matched',matched_type=p_matched_type,matched_id=p_matched_id where id=p_line_id;end;$$;

create or replace function public.unmatch_bank_statement_line(p_company_id uuid,p_line_id uuid)
returns void language plpgsql volatile security definer set search_path='' as $$ begin if not public.current_user_has_permission(p_company_id,'settings.manage') then raise exception using errcode='42501',message='Tidak memiliki izin unmatch bank.';end if;update public.bank_statement_lines line set status='unmatched',matched_type=null,matched_id=null from public.bank_reconciliations reconciliation where line.id=p_line_id and line.company_id=p_company_id and reconciliation.id=line.reconciliation_id and reconciliation.status='draft' and line.status='matched';if not found then raise exception using message='Baris matched tidak ditemukan.';end if;end;$$;

create or replace function public.create_reconciliation_adjustment(p_company_id uuid,p_line_id uuid,p_offset_account_id uuid,p_description text,p_idempotency_key text)
returns uuid language plpgsql volatile security definer set search_path='' as $$
declare v_line public.bank_statement_lines%rowtype;v_doc public.bank_reconciliations%rowtype;v_bank_gl uuid;v_journal uuid;v_amount numeric;
begin if not public.current_user_has_permission(p_company_id,'journal.post') or not public.current_user_has_permission(p_company_id,'settings.manage') then raise exception using errcode='42501',message='Tidak memiliki izin membuat adjustment rekonsiliasi.';end if;if length(trim(p_description))<5 then raise exception using message='Keterangan adjustment minimal lima karakter.';end if;select line.* into v_line from public.bank_statement_lines line join public.bank_reconciliations reconciliation on reconciliation.id=line.reconciliation_id where line.company_id=p_company_id and line.id=p_line_id and line.status='unmatched' and reconciliation.status='draft' for update;if not found then raise exception using message='Baris unmatched tidak ditemukan.';end if;select * into v_doc from public.bank_reconciliations where id=v_line.reconciliation_id;if not exists(select 1 from public.accounting_periods where company_id=p_company_id and v_line.transaction_date between starts_on and ends_on and status='open') then raise exception using message='Periode akuntansi tidak terbuka.';end if;select gl_account_id into v_bank_gl from public.bank_accounts where company_id=p_company_id and id=v_doc.bank_account_id;if not exists(select 1 from public.chart_of_accounts where company_id=p_company_id and id=p_offset_account_id and is_active and allow_manual_entry) then raise exception using message='Akun lawan adjustment tidak valid.';end if;v_amount:=abs(v_line.amount);
 insert into public.journal_entries(company_id,journal_number,document_date,journal_date,posting_date,description,status,source_type,source_id,total_debit,total_credit,idempotency_key,posted_by,posted_at,created_by) values(p_company_id,'BR-ADJ-'||substr(v_line.id::text,1,8),v_line.transaction_date,v_line.transaction_date,v_line.transaction_date,trim(p_description),'posted','bank_reconciliation_adjustment',v_line.id,v_amount,v_amount,p_idempotency_key,auth.uid(),now(),auth.uid()) returning id into v_journal;
 insert into public.journal_lines(company_id,journal_entry_id,account_id,line_number,description,debit,credit,base_debit,base_credit,created_by) values(p_company_id,v_journal,case when v_line.amount>0 then v_bank_gl else p_offset_account_id end,1,trim(p_description),v_amount,0,v_amount,0,auth.uid()),(p_company_id,v_journal,case when v_line.amount>0 then p_offset_account_id else v_bank_gl end,2,trim(p_description),0,v_amount,0,v_amount,auth.uid());update public.bank_statement_lines set status='adjusted',adjustment_journal_id=v_journal where id=p_line_id;return v_journal;
exception when unique_violation then select adjustment_journal_id into v_journal from public.bank_statement_lines where id=p_line_id;return v_journal;end;$$;

create or replace function public.finalize_bank_reconciliation(p_company_id uuid,p_reconciliation_id uuid)
returns void language plpgsql volatile security definer set search_path='' as $$ declare v_doc public.bank_reconciliations%rowtype;v_total numeric;begin if not public.current_user_has_permission(p_company_id,'settings.manage') then raise exception using errcode='42501',message='Tidak memiliki izin finalisasi rekonsiliasi.';end if;select * into v_doc from public.bank_reconciliations where company_id=p_company_id and id=p_reconciliation_id and status='draft' for update;if not found then raise exception using message='Draft rekonsiliasi tidak ditemukan.';end if;if exists(select 1 from public.bank_statement_lines where reconciliation_id=p_reconciliation_id and status='unmatched') then raise exception using message='Semua baris statement harus matched atau adjusted.';end if;select coalesce(sum(amount),0) into v_total from public.bank_statement_lines where reconciliation_id=p_reconciliation_id;if round(v_doc.opening_balance+v_total,4)<>v_doc.closing_balance then raise exception using message='Saldo pembukaan ditambah mutasi tidak sama dengan saldo penutupan.';end if;update public.bank_reconciliations set status='finalized',finalized_by=auth.uid(),finalized_at=now(),updated_by=auth.uid() where id=p_reconciliation_id;end;$$;

revoke all on function public.save_bank_reconciliation(uuid,uuid,jsonb,jsonb,integer) from public,anon;revoke all on function public.match_bank_statement_line(uuid,uuid,text,uuid) from public,anon;revoke all on function public.unmatch_bank_statement_line(uuid,uuid) from public,anon;revoke all on function public.create_reconciliation_adjustment(uuid,uuid,uuid,text,text) from public,anon;revoke all on function public.finalize_bank_reconciliation(uuid,uuid) from public,anon;
grant execute on function public.save_bank_reconciliation(uuid,uuid,jsonb,jsonb,integer) to authenticated;grant execute on function public.match_bank_statement_line(uuid,uuid,text,uuid) to authenticated;grant execute on function public.unmatch_bank_statement_line(uuid,uuid) to authenticated;grant execute on function public.create_reconciliation_adjustment(uuid,uuid,uuid,text,text) to authenticated;grant execute on function public.finalize_bank_reconciliation(uuid,uuid) to authenticated;

commit;
